Support LWAN web server
eecheng87/ESCA pull request #25
Opened 2022-06-11 09:58 UTC by yaohwang99

This commit is the first try to support LWAN web server.
The changes includes:
Add patches for lwan.
Add script to CMakelist.txt to link library.
Add lwan-preload.c wrapper for lwan.
Add send() system call to wrapper.c.

When there is only one connection from the browser,
only send() will be called.
When there are  multiple connections, send() will be called
once and then sendfile() will be called.

2022-06-11 10:02 UTC, jserv commented on wrapper/lwan-preload.c
> + * Authored by Steven Cheng <yucheng871011@gmail.com>
Replace with your name here.

2022-06-11 10:03 UTC, jserv commented on configs/lwan.conf
> +#tls_listener *:8081 {
Minimize the necessary changes. That is, keep the required parts.

2022-06-11 10:54 UTC, eecheng87 commented
Thanks for PR. There is a grammar error in the commit message.
Instead "The changes includes", it should be "The changes include".

2022-06-11 10:55 UTC, eecheng87 commented
@yaohwang99 , please also updates README.

2022-06-11 10:57 UTC, jserv requested changes
Append "Close #20" at the end of git commit message(s). Once this pull request is merged, issue #20 would be closed automatically.

2022-06-12 12:04 UTC, jserv commented on wrapper/wrapper.c
> +        real_send ? real_send : dlsym(RTLD_NEXT, "send");
Add an extra blank line after `send` statement.

2022-06-14 11:54 UTC, merged